import type { Config } from '@sveltejs/kit'

export const config: Config = {
  isr: {
    // Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
    // Setting the value to `false` means it will never expire.
    expiration: false
  }
}